# Generated by Django 5.2.7 on 2025-10-07 20:46
# Adds an optional import prompt override to AI providers.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookbook", "0231_alter_aiprovider_options_alter_automation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiprovider",
            name="import_prompt",
            field=models.TextField(blank=True, default=""),
        ),
    ]
