/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface ExportRequestCustomFilter
 */
export interface ExportRequestCustomFilter {
    /**
     * 
     * @type {number}
     * @memberof ExportRequestCustomFilter
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExportRequestCustomFilter
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExportRequestCustomFilter
     */
    search: string;
    /**
     * 
     * @type {Array<User>}
     * @memberof ExportRequestCustomFilter
     */
    shared?: Array<User>;
    /**
     * 
     * @type {number}
     * @memberof ExportRequestCustomFilter
     */
    readonly createdBy: number;
}

/**
 * Check if a given object implements the ExportRequestCustomFilter interface.
 */
export function instanceOfExportRequestCustomFilter(value: object): value is ExportRequestCustomFilter {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('search' in value) || value['search'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    return true;
}

export function ExportRequestCustomFilterFromJSON(json: any): ExportRequestCustomFilter {
    return ExportRequestCustomFilterFromJSONTyped(json, false);
}

export function ExportRequestCustomFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportRequestCustomFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'search': json['search'],
        'shared': json['shared'] == null ? undefined : ((json['shared'] as Array<any>).map(UserFromJSON)),
        'createdBy': json['created_by'],
    };
}

export function ExportRequestCustomFilterToJSON(value?: ExportRequestCustomFilter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'search': value['search'],
        'shared': value['shared'] == null ? undefined : ((value['shared'] as Array<any>).map(UserToJSON)),
    };
}

