/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FoodSupermarketCategory
 */
export interface FoodSupermarketCategory {
    /**
     * 
     * @type {number}
     * @memberof FoodSupermarketCategory
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FoodSupermarketCategory
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FoodSupermarketCategory
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FoodSupermarketCategory
     */
    openDataSlug?: string | null;
}

/**
 * Check if a given object implements the FoodSupermarketCategory interface.
 */
export function instanceOfFoodSupermarketCategory(value: object): value is FoodSupermarketCategory {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FoodSupermarketCategoryFromJSON(json: any): FoodSupermarketCategory {
    return FoodSupermarketCategoryFromJSONTyped(json, false);
}

export function FoodSupermarketCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodSupermarketCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'openDataSlug': json['open_data_slug'] == null ? undefined : json['open_data_slug'],
    };
}

export function FoodSupermarketCategoryToJSON(value?: FoodSupermarketCategory | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'open_data_slug': value['openDataSlug'],
    };
}

