/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FoodRecipe
 */
export interface FoodRecipe {
    /**
     * 
     * @type {number}
     * @memberof FoodRecipe
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FoodRecipe
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FoodRecipe
     */
    readonly url: string;
}

/**
 * Check if a given object implements the FoodRecipe interface.
 */
export function instanceOfFoodRecipe(value: object): value is FoodRecipe {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function FoodRecipeFromJSON(json: any): FoodRecipe {
    return FoodRecipeFromJSONTyped(json, false);
}

export function FoodRecipeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodRecipe {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'url': json['url'],
    };
}

export function FoodRecipeToJSON(value?: FoodRecipe | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

