/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FoodPropertiesFoodUnit
 */
export interface FoodPropertiesFoodUnit {
    /**
     * 
     * @type {number}
     * @memberof FoodPropertiesFoodUnit
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FoodPropertiesFoodUnit
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FoodPropertiesFoodUnit
     */
    pluralName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FoodPropertiesFoodUnit
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FoodPropertiesFoodUnit
     */
    baseUnit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FoodPropertiesFoodUnit
     */
    openDataSlug?: string | null;
}

/**
 * Check if a given object implements the FoodPropertiesFoodUnit interface.
 */
export function instanceOfFoodPropertiesFoodUnit(value: object): value is FoodPropertiesFoodUnit {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FoodPropertiesFoodUnitFromJSON(json: any): FoodPropertiesFoodUnit {
    return FoodPropertiesFoodUnitFromJSONTyped(json, false);
}

export function FoodPropertiesFoodUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodPropertiesFoodUnit {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'pluralName': json['plural_name'] == null ? undefined : json['plural_name'],
        'description': json['description'] == null ? undefined : json['description'],
        'baseUnit': json['base_unit'] == null ? undefined : json['base_unit'],
        'openDataSlug': json['open_data_slug'] == null ? undefined : json['open_data_slug'],
    };
}

export function FoodPropertiesFoodUnitToJSON(value?: FoodPropertiesFoodUnit | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'plural_name': value['pluralName'],
        'description': value['description'],
        'base_unit': value['baseUnit'],
        'open_data_slug': value['openDataSlug'],
    };
}

