/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface IngredientFood
 */
export interface IngredientFood {
    /**
     * 
     * @type {number}
     * @memberof IngredientFood
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IngredientFood
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IngredientFood
     */
    pluralName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IngredientFood
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof IngredientFood
     */
    readonly shopping: string;
    /**
     * 
     * @type {FoodRecipe}
     * @memberof IngredientFood
     */
    recipe?: FoodRecipe | null;
    /**
     * 
     * @type {string}
     * @memberof IngredientFood
     */
    url?: string | null;
    /**
     * 
     * @type {Array<Property>}
     * @memberof IngredientFood
     */
    properties?: Array<Property> | null;
    /**
     * 
     * @type {number}
     * @memberof IngredientFood
     */
    propertiesFoodAmount?: number;
    /**
     * 
     * @type {FoodPropertiesFoodUnit}
     * @memberof IngredientFood
     */
    propertiesFoodUnit?: FoodPropertiesFoodUnit | null;
    /**
     * 
     * @type {number}
     * @memberof IngredientFood
     */
    fdcId?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof IngredientFood
     */
    foodOnhand?: boolean | null;
    /**
     * 
     * @type {FoodSupermarketCategory}
     * @memberof IngredientFood
     */
    supermarketCategory?: FoodSupermarketCategory | null;
    /**
     * 
     * @type {number}
     * @memberof IngredientFood
     */
    readonly parent: number;
    /**
     * 
     * @type {number}
     * @memberof IngredientFood
     */
    readonly numchild: number;
    /**
     * 
     * @type {Array<FoodInheritField>}
     * @memberof IngredientFood
     */
    inheritFields?: Array<FoodInheritField> | null;
    /**
     * Returns a string representation of a tree node and it's ancestors,
     * e.g. 'Cuisine > Asian > Chinese > Catonese'.
     * @type {string}
     * @memberof IngredientFood
     */
    readonly fullName: string;
    /**
     * 
     * @type {boolean}
     * @memberof IngredientFood
     */
    ignoreShopping?: boolean;
    /**
     * 
     * @type {Array<FoodSimple>}
     * @memberof IngredientFood
     */
    substitute?: Array<FoodSimple> | null;
    /**
     * 
     * @type {boolean}
     * @memberof IngredientFood
     */
    substituteSiblings?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IngredientFood
     */
    substituteChildren?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IngredientFood
     */
    readonly substituteOnhand: boolean;
    /**
     * 
     * @type {Array<FoodInheritField>}
     * @memberof IngredientFood
     */
    childInheritFields?: Array<FoodInheritField> | null;
    /**
     * 
     * @type {string}
     * @memberof IngredientFood
     */
    openDataSlug?: string | null;
}

/**
 * Check if a given object implements the IngredientFood interface.
 */
export function instanceOfIngredientFood(value: object): value is IngredientFood {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('shopping' in value) || value['shopping'] === undefined) return false;
    if (!('parent' in value) || value['parent'] === undefined) return false;
    if (!('numchild' in value) || value['numchild'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('substituteOnhand' in value) || value['substituteOnhand'] === undefined) return false;
    return true;
}

export function IngredientFoodFromJSON(json: any): IngredientFood {
    return IngredientFoodFromJSONTyped(json, false);
}

export function IngredientFoodFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientFood {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'pluralName': json['plural_name'] == null ? undefined : json['plural_name'],
        'description': json['description'] == null ? undefined : json['description'],
        'shopping': json['shopping'],
        'recipe': json['recipe'] == null ? undefined : FoodRecipeFromJSON(json['recipe']),
        'url': json['url'] == null ? undefined : json['url'],
        'properties': json['properties'] == null ? undefined : ((json['properties'] as Array<any>).map(PropertyFromJSON)),
        'propertiesFoodAmount': json['properties_food_amount'] == null ? undefined : json['properties_food_amount'],
        'propertiesFoodUnit': json['properties_food_unit'] == null ? undefined : FoodPropertiesFoodUnitFromJSON(json['properties_food_unit']),
        'fdcId': json['fdc_id'] == null ? undefined : json['fdc_id'],
        'foodOnhand': json['food_onhand'] == null ? undefined : json['food_onhand'],
        'supermarketCategory': json['supermarket_category'] == null ? undefined : FoodSupermarketCategoryFromJSON(json['supermarket_category']),
        'parent': json['parent'],
        'numchild': json['numchild'],
        'inheritFields': json['inherit_fields'] == null ? undefined : ((json['inherit_fields'] as Array<any>).map(FoodInheritFieldFromJSON)),
        'fullName': json['full_name'],
        'ignoreShopping': json['ignore_shopping'] == null ? undefined : json['ignore_shopping'],
        'substitute': json['substitute'] == null ? undefined : ((json['substitute'] as Array<any>).map(FoodSimpleFromJSON)),
        'substituteSiblings': json['substitute_siblings'] == null ? undefined : json['substitute_siblings'],
        'substituteChildren': json['substitute_children'] == null ? undefined : json['substitute_children'],
        'substituteOnhand': json['substitute_onhand'],
        'childInheritFields': json['child_inherit_fields'] == null ? undefined : ((json['child_inherit_fields'] as Array<any>).map(FoodInheritFieldFromJSON)),
        'openDataSlug': json['open_data_slug'] == null ? undefined : json['open_data_slug'],
    };
}

export function IngredientFoodToJSON(value?: IngredientFood | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'plural_name': value['pluralName'],
        'description': value['description'],
        'recipe': FoodRecipeToJSON(value['recipe']),
        'url': value['url'],
        'properties': value['properties'] == null ? undefined : ((value['properties'] as Array<any>).map(PropertyToJSON)),
        'properties_food_amount': value['propertiesFoodAmount'],
        'properties_food_unit': FoodPropertiesFoodUnitToJSON(value['propertiesFoodUnit']),
        'fdc_id': value['fdcId'],
        'food_onhand': value['foodOnhand'],
        'supermarket_category': FoodSupermarketCategoryToJSON(value['supermarketCategory']),
        'inherit_fields': value['inheritFields'] == null ? undefined : ((value['inheritFields'] as Array<any>).map(FoodInheritFieldToJSON)),
        'ignore_shopping': value['ignoreShopping'],
        'substitute': value['substitute'] == null ? undefined : ((value['substitute'] as Array<any>).map(FoodSimpleToJSON)),
        'substitute_siblings': value['substituteSiblings'],
        'substitute_children': value['substituteChildren'],
        'child_inherit_fields': value['childInheritFields'] == null ? undefined : ((value['childInheritFields'] as Array<any>).map(FoodInheritFieldToJSON)),
        'open_data_slug': value['openDataSlug'],
    };
}

