/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface MealPlanRecipe
 */
export interface MealPlanRecipe {
    /**
     * 
     * @type {number}
     * @memberof MealPlanRecipe
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MealPlanRecipe
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MealPlanRecipe
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MealPlanRecipe
     */
    readonly image: string | null;
    /**
     * 
     * @type {Array<KeywordLabel>}
     * @memberof MealPlanRecipe
     */
    readonly keywords: Array<KeywordLabel>;
    /**
     * 
     * @type {number}
     * @memberof MealPlanRecipe
     */
    readonly workingTime: number;
    /**
     * 
     * @type {number}
     * @memberof MealPlanRecipe
     */
    readonly waitingTime: number;
    /**
     * 
     * @type {User}
     * @memberof MealPlanRecipe
     */
    readonly createdBy: User;
    /**
     * 
     * @type {Date}
     * @memberof MealPlanRecipe
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof MealPlanRecipe
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof MealPlanRecipe
     */
    readonly internal: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MealPlanRecipe
     */
    _private?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MealPlanRecipe
     */
    readonly servings: number;
    /**
     * 
     * @type {string}
     * @memberof MealPlanRecipe
     */
    readonly servingsText: string;
    /**
     * 
     * @type {number}
     * @memberof MealPlanRecipe
     */
    readonly rating: number | null;
    /**
     * 
     * @type {Date}
     * @memberof MealPlanRecipe
     */
    readonly lastCooked: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof MealPlanRecipe
     */
    readonly _new: boolean;
    /**
     * 
     * @type {string}
     * @memberof MealPlanRecipe
     */
    readonly recent: string;
}

/**
 * Check if a given object implements the MealPlanRecipe interface.
 */
export function instanceOfMealPlanRecipe(value: object): value is MealPlanRecipe {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('keywords' in value) || value['keywords'] === undefined) return false;
    if (!('workingTime' in value) || value['workingTime'] === undefined) return false;
    if (!('waitingTime' in value) || value['waitingTime'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('internal' in value) || value['internal'] === undefined) return false;
    if (!('servings' in value) || value['servings'] === undefined) return false;
    if (!('servingsText' in value) || value['servingsText'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('lastCooked' in value) || value['lastCooked'] === undefined) return false;
    if (!('_new' in value) || value['_new'] === undefined) return false;
    if (!('recent' in value) || value['recent'] === undefined) return false;
    return true;
}

export function MealPlanRecipeFromJSON(json: any): MealPlanRecipe {
    return MealPlanRecipeFromJSONTyped(json, false);
}

export function MealPlanRecipeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MealPlanRecipe {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'image': json['image'],
        'keywords': ((json['keywords'] as Array<any>).map(KeywordLabelFromJSON)),
        'workingTime': json['working_time'],
        'waitingTime': json['waiting_time'],
        'createdBy': UserFromJSON(json['created_by']),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'internal': json['internal'],
        '_private': json['private'] == null ? undefined : json['private'],
        'servings': json['servings'],
        'servingsText': json['servings_text'],
        'rating': json['rating'],
        'lastCooked': (json['last_cooked'] == null ? null : new Date(json['last_cooked'])),
        '_new': json['new'],
        'recent': json['recent'],
    };
}

export function MealPlanRecipeToJSON(value?: MealPlanRecipe | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'private': value['_private'],
    };
}

