/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedSpaceAiDefaultProvider
 */
export interface PatchedSpaceAiDefaultProvider {
    /**
     * 
     * @type {number}
     * @memberof PatchedSpaceAiDefaultProvider
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedSpaceAiDefaultProvider
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSpaceAiDefaultProvider
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSpaceAiDefaultProvider
     */
    importPrompt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedSpaceAiDefaultProvider
     */
    apiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSpaceAiDefaultProvider
     */
    modelName: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSpaceAiDefaultProvider
     */
    url?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedSpaceAiDefaultProvider
     */
    logCreditCost?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedSpaceAiDefaultProvider
     */
    space?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSpaceAiDefaultProvider
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSpaceAiDefaultProvider
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedSpaceAiDefaultProvider
     */
    readonly defaultImportPrompt: string;
}

/**
 * Check if a given object implements the PatchedSpaceAiDefaultProvider interface.
 */
export function instanceOfPatchedSpaceAiDefaultProvider(value: object): value is PatchedSpaceAiDefaultProvider {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('modelName' in value) || value['modelName'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('defaultImportPrompt' in value) || value['defaultImportPrompt'] === undefined) return false;
    return true;
}

export function PatchedSpaceAiDefaultProviderFromJSON(json: any): PatchedSpaceAiDefaultProvider {
    return PatchedSpaceAiDefaultProviderFromJSONTyped(json, false);
}

export function PatchedSpaceAiDefaultProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSpaceAiDefaultProvider {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'importPrompt': json['import_prompt'] == null ? undefined : json['import_prompt'],
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'modelName': json['model_name'],
        'url': json['url'] == null ? undefined : json['url'],
        'logCreditCost': json['log_credit_cost'] == null ? undefined : json['log_credit_cost'],
        'space': json['space'] == null ? undefined : json['space'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'defaultImportPrompt': json['default_import_prompt'],
    };
}

export function PatchedSpaceAiDefaultProviderToJSON(value?: PatchedSpaceAiDefaultProvider | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'import_prompt': value['importPrompt'],
        'api_key': value['apiKey'],
        'model_name': value['modelName'],
        'url': value['url'],
        'log_credit_cost': value['logCreditCost'],
        'space': value['space'],
    };
}

