/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface PatchedSpaceImage
 */
export interface PatchedSpaceImage {
    /**
     * 
     * @type {number}
     * @memberof PatchedSpaceImage
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedSpaceImage
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSpaceImage
     */
    readonly fileDownload: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSpaceImage
     */
    readonly preview: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedSpaceImage
     */
    readonly fileSizeKb: number;
    /**
     * 
     * @type {User}
     * @memberof PatchedSpaceImage
     */
    readonly createdBy: User;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSpaceImage
     */
    readonly createdAt: Date;
}

/**
 * Check if a given object implements the PatchedSpaceImage interface.
 */
export function instanceOfPatchedSpaceImage(value: object): value is PatchedSpaceImage {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('fileDownload' in value) || value['fileDownload'] === undefined) return false;
    if (!('preview' in value) || value['preview'] === undefined) return false;
    if (!('fileSizeKb' in value) || value['fileSizeKb'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PatchedSpaceImageFromJSON(json: any): PatchedSpaceImage {
    return PatchedSpaceImageFromJSONTyped(json, false);
}

export function PatchedSpaceImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSpaceImage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'fileDownload': json['file_download'],
        'preview': json['preview'],
        'fileSizeKb': json['file_size_kb'],
        'createdBy': UserFromJSON(json['created_by']),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function PatchedSpaceImageToJSON(value?: PatchedSpaceImage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

