/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * Adds nested create feature
 * @export
 * @interface SearchPreference
 */
export interface SearchPreference {
    /**
     * 
     * @type {User}
     * @memberof SearchPreference
     */
    readonly user: User;
    /**
     * 
     * @type {SearchEnum}
     * @memberof SearchPreference
     */
    search?: SearchEnum;
    /**
     * 
     * @type {boolean}
     * @memberof SearchPreference
     */
    lookup?: boolean;
    /**
     * 
     * @type {Array<SearchFields>}
     * @memberof SearchPreference
     */
    unaccent?: Array<SearchFields> | null;
    /**
     * 
     * @type {Array<SearchFields>}
     * @memberof SearchPreference
     */
    icontains?: Array<SearchFields> | null;
    /**
     * 
     * @type {Array<SearchFields>}
     * @memberof SearchPreference
     */
    istartswith?: Array<SearchFields> | null;
    /**
     * 
     * @type {Array<SearchFields>}
     * @memberof SearchPreference
     */
    trigram?: Array<SearchFields> | null;
    /**
     * 
     * @type {Array<SearchFields>}
     * @memberof SearchPreference
     */
    fulltext?: Array<SearchFields> | null;
    /**
     * 
     * @type {number}
     * @memberof SearchPreference
     */
    trigramThreshold?: number;
}

/**
 * Check if a given object implements the SearchPreference interface.
 */
export function instanceOfSearchPreference(value: object): value is SearchPreference {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function SearchPreferenceFromJSON(json: any): SearchPreference {
    return SearchPreferenceFromJSONTyped(json, false);
}

export function SearchPreferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPreference {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
        'search': json['search'] == null ? undefined : SearchEnumFromJSON(json['search']),
        'lookup': json['lookup'] == null ? undefined : json['lookup'],
        'unaccent': json['unaccent'] == null ? undefined : ((json['unaccent'] as Array<any>).map(SearchFieldsFromJSON)),
        'icontains': json['icontains'] == null ? undefined : ((json['icontains'] as Array<any>).map(SearchFieldsFromJSON)),
        'istartswith': json['istartswith'] == null ? undefined : ((json['istartswith'] as Array<any>).map(SearchFieldsFromJSON)),
        'trigram': json['trigram'] == null ? undefined : ((json['trigram'] as Array<any>).map(SearchFieldsFromJSON)),
        'fulltext': json['fulltext'] == null ? undefined : ((json['fulltext'] as Array<any>).map(SearchFieldsFromJSON)),
        'trigramThreshold': json['trigram_threshold'] == null ? undefined : json['trigram_threshold'],
    };
}

export function SearchPreferenceToJSON(value?: SearchPreference | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'search': SearchEnumToJSON(value['search']),
        'lookup': value['lookup'],
        'unaccent': value['unaccent'] == null ? undefined : ((value['unaccent'] as Array<any>).map(SearchFieldsToJSON)),
        'icontains': value['icontains'] == null ? undefined : ((value['icontains'] as Array<any>).map(SearchFieldsToJSON)),
        'istartswith': value['istartswith'] == null ? undefined : ((value['istartswith'] as Array<any>).map(SearchFieldsToJSON)),
        'trigram': value['trigram'] == null ? undefined : ((value['trigram'] as Array<any>).map(SearchFieldsToJSON)),
        'fulltext': value['fulltext'] == null ? undefined : ((value['fulltext'] as Array<any>).map(SearchFieldsToJSON)),
        'trigram_threshold': value['trigramThreshold'],
    };
}

