/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * Adds nested create feature
 * @export
 * @interface Space
 */
export interface Space {
    /**
     * 
     * @type {number}
     * @memberof Space
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Space
     */
    name?: string;
    /**
     * 
     * @type {User}
     * @memberof Space
     */
    readonly createdBy: User;
    /**
     * 
     * @type {Date}
     * @memberof Space
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Space
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof Space
     */
    readonly maxRecipes: number;
    /**
     * Maximum file storage for space in MB. 0 for unlimited, -1 to disable file upload.
     * @type {number}
     * @memberof Space
     */
    readonly maxFileStorageMb: number;
    /**
     * 
     * @type {number}
     * @memberof Space
     */
    readonly maxUsers: number;
    /**
     * 
     * @type {boolean}
     * @memberof Space
     */
    readonly allowSharing: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Space
     */
    readonly demo: boolean;
    /**
     * 
     * @type {Array<FoodInheritField>}
     * @memberof Space
     */
    foodInherit?: Array<FoodInheritField>;
    /**
     * 
     * @type {number}
     * @memberof Space
     */
    readonly userCount: number;
    /**
     * 
     * @type {number}
     * @memberof Space
     */
    readonly recipeCount: number;
    /**
     * 
     * @type {number}
     * @memberof Space
     */
    readonly fileSizeMb: number;
    /**
     * 
     * @type {PatchedSpaceImage}
     * @memberof Space
     */
    image?: PatchedSpaceImage | null;
    /**
     * 
     * @type {PatchedSpaceImage}
     * @memberof Space
     */
    navLogo?: PatchedSpaceImage | null;
    /**
     * 
     * @type {SpaceThemeEnum}
     * @memberof Space
     */
    spaceTheme?: SpaceThemeEnum;
    /**
     * 
     * @type {PatchedSpaceImage}
     * @memberof Space
     */
    customSpaceTheme?: PatchedSpaceImage | null;
    /**
     * 
     * @type {string}
     * @memberof Space
     */
    navBgColor?: string;
    /**
     * 
     * @type {SpaceNavTextColorEnum}
     * @memberof Space
     */
    navTextColor?: SpaceNavTextColorEnum;
    /**
     * 
     * @type {PatchedSpaceImage}
     * @memberof Space
     */
    logoColor32?: PatchedSpaceImage | null;
    /**
     * 
     * @type {PatchedSpaceImage}
     * @memberof Space
     */
    logoColor128?: PatchedSpaceImage | null;
    /**
     * 
     * @type {PatchedSpaceImage}
     * @memberof Space
     */
    logoColor144?: PatchedSpaceImage | null;
    /**
     * 
     * @type {PatchedSpaceImage}
     * @memberof Space
     */
    logoColor180?: PatchedSpaceImage | null;
    /**
     * 
     * @type {PatchedSpaceImage}
     * @memberof Space
     */
    logoColor192?: PatchedSpaceImage | null;
    /**
     * 
     * @type {PatchedSpaceImage}
     * @memberof Space
     */
    logoColor512?: PatchedSpaceImage | null;
    /**
     * 
     * @type {PatchedSpaceImage}
     * @memberof Space
     */
    logoColorSvg?: PatchedSpaceImage | null;
    /**
     * 
     * @type {number}
     * @memberof Space
     */
    aiCreditsMonthly?: number;
    /**
     * 
     * @type {number}
     * @memberof Space
     */
    aiCreditsBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof Space
     */
    readonly aiMonthlyCreditsUsed: number;
    /**
     * 
     * @type {boolean}
     * @memberof Space
     */
    aiEnabled?: boolean;
    /**
     * 
     * @type {PatchedSpaceAiDefaultProvider}
     * @memberof Space
     */
    aiDefaultProvider?: PatchedSpaceAiDefaultProvider | null;
    /**
     * 
     * @type {boolean}
     * @memberof Space
     */
    spaceSetupCompleted?: boolean;
}

/**
 * Check if a given object implements the Space interface.
 */
export function instanceOfSpace(value: object): value is Space {
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('maxRecipes' in value) || value['maxRecipes'] === undefined) return false;
    if (!('maxFileStorageMb' in value) || value['maxFileStorageMb'] === undefined) return false;
    if (!('maxUsers' in value) || value['maxUsers'] === undefined) return false;
    if (!('allowSharing' in value) || value['allowSharing'] === undefined) return false;
    if (!('demo' in value) || value['demo'] === undefined) return false;
    if (!('userCount' in value) || value['userCount'] === undefined) return false;
    if (!('recipeCount' in value) || value['recipeCount'] === undefined) return false;
    if (!('fileSizeMb' in value) || value['fileSizeMb'] === undefined) return false;
    if (!('aiMonthlyCreditsUsed' in value) || value['aiMonthlyCreditsUsed'] === undefined) return false;
    return true;
}

export function SpaceFromJSON(json: any): Space {
    return SpaceFromJSONTyped(json, false);
}

export function SpaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Space {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdBy': UserFromJSON(json['created_by']),
        'createdAt': (new Date(json['created_at'])),
        'message': json['message'] == null ? undefined : json['message'],
        'maxRecipes': json['max_recipes'],
        'maxFileStorageMb': json['max_file_storage_mb'],
        'maxUsers': json['max_users'],
        'allowSharing': json['allow_sharing'],
        'demo': json['demo'],
        'foodInherit': json['food_inherit'] == null ? undefined : ((json['food_inherit'] as Array<any>).map(FoodInheritFieldFromJSON)),
        'userCount': json['user_count'],
        'recipeCount': json['recipe_count'],
        'fileSizeMb': json['file_size_mb'],
        'image': json['image'] == null ? undefined : PatchedSpaceImageFromJSON(json['image']),
        'navLogo': json['nav_logo'] == null ? undefined : PatchedSpaceImageFromJSON(json['nav_logo']),
        'spaceTheme': json['space_theme'] == null ? undefined : SpaceThemeEnumFromJSON(json['space_theme']),
        'customSpaceTheme': json['custom_space_theme'] == null ? undefined : PatchedSpaceImageFromJSON(json['custom_space_theme']),
        'navBgColor': json['nav_bg_color'] == null ? undefined : json['nav_bg_color'],
        'navTextColor': json['nav_text_color'] == null ? undefined : SpaceNavTextColorEnumFromJSON(json['nav_text_color']),
        'logoColor32': json['logo_color_32'] == null ? undefined : PatchedSpaceImageFromJSON(json['logo_color_32']),
        'logoColor128': json['logo_color_128'] == null ? undefined : PatchedSpaceImageFromJSON(json['logo_color_128']),
        'logoColor144': json['logo_color_144'] == null ? undefined : PatchedSpaceImageFromJSON(json['logo_color_144']),
        'logoColor180': json['logo_color_180'] == null ? undefined : PatchedSpaceImageFromJSON(json['logo_color_180']),
        'logoColor192': json['logo_color_192'] == null ? undefined : PatchedSpaceImageFromJSON(json['logo_color_192']),
        'logoColor512': json['logo_color_512'] == null ? undefined : PatchedSpaceImageFromJSON(json['logo_color_512']),
        'logoColorSvg': json['logo_color_svg'] == null ? undefined : PatchedSpaceImageFromJSON(json['logo_color_svg']),
        'aiCreditsMonthly': json['ai_credits_monthly'] == null ? undefined : json['ai_credits_monthly'],
        'aiCreditsBalance': json['ai_credits_balance'] == null ? undefined : json['ai_credits_balance'],
        'aiMonthlyCreditsUsed': json['ai_monthly_credits_used'],
        'aiEnabled': json['ai_enabled'] == null ? undefined : json['ai_enabled'],
        'aiDefaultProvider': json['ai_default_provider'] == null ? undefined : PatchedSpaceAiDefaultProviderFromJSON(json['ai_default_provider']),
        'spaceSetupCompleted': json['space_setup_completed'] == null ? undefined : json['space_setup_completed'],
    };
}

export function SpaceToJSON(value?: Space | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'message': value['message'],
        'food_inherit': value['foodInherit'] == null ? undefined : ((value['foodInherit'] as Array<any>).map(FoodInheritFieldToJSON)),
        'image': PatchedSpaceImageToJSON(value['image']),
        'nav_logo': PatchedSpaceImageToJSON(value['navLogo']),
        'space_theme': SpaceThemeEnumToJSON(value['spaceTheme']),
        'custom_space_theme': PatchedSpaceImageToJSON(value['customSpaceTheme']),
        'nav_bg_color': value['navBgColor'],
        'nav_text_color': SpaceNavTextColorEnumToJSON(value['navTextColor']),
        'logo_color_32': PatchedSpaceImageToJSON(value['logoColor32']),
        'logo_color_128': PatchedSpaceImageToJSON(value['logoColor128']),
        'logo_color_144': PatchedSpaceImageToJSON(value['logoColor144']),
        'logo_color_180': PatchedSpaceImageToJSON(value['logoColor180']),
        'logo_color_192': PatchedSpaceImageToJSON(value['logoColor192']),
        'logo_color_512': PatchedSpaceImageToJSON(value['logoColor512']),
        'logo_color_svg': PatchedSpaceImageToJSON(value['logoColorSvg']),
        'ai_credits_monthly': value['aiCreditsMonthly'],
        'ai_credits_balance': value['aiCreditsBalance'],
        'ai_enabled': value['aiEnabled'],
        'ai_default_provider': PatchedSpaceAiDefaultProviderToJSON(value['aiDefaultProvider']),
        'space_setup_completed': value['spaceSetupCompleted'],
    };
}

